require('dotenv').config();
const { Idioma }= require('../db')


async function idiomaLoad(){
    
    Idioma.bulkCreate([
        { id:1, page : 'HOME', lang: 'ENG', texto:'No Recipes Found'},
        { id:2, page : 'HOME', lang: 'SPA', texto:'Receta inexistente'},
        { id:3, page : 'HOME', lang: 'ENG', texto:'No Recipes Found'},
        { id:4, page : 'HOME', lang: 'SPA', texto:'Receta inexistente'},
        { id:5, page : 'DETAIL', lang: 'ENG', texto:'Instructions'},
        { id:6, page : 'DETAIL', lang: 'SPA', texto:'Instrucciones'},
        { id:7, page : 'DETAIL', lang: 'ENG', texto:'Healh Score'},
        { id:8, page : 'DETAIL', lang: 'SPA', texto:'Puntuacion de Salud'},
        { id:9, page : 'DETAIL', lang: 'ENG', texto:'Likes'},
        { id:10, page : 'DETAIL', lang: 'SPA', texto:'Me gusta'},
        { id:11, page : 'DETAIL', lang: 'ENG', texto:'Diets'},
        { id:12, page : 'DETAIL', lang: 'SPA', texto:'Dietas'},
        { id:13, page : 'DETAIL', lang: 'ENG', texto:'Dish Types'},
        { id:14, page : 'DETAIL', lang: 'SPA', texto:'Tipo de Plato'},
        { id:16, page : 'NAV', lang: 'ENG', texto:'HOME'},
        { id:17, page : 'NAV', lang: 'SPA', texto:'Pagina Principal'},
        { id:18, page : 'NAV', lang: 'ENG', texto:'Create Recipe'},
        { id:19, page : 'NAV', lang: 'SPA', texto:'Crear Receta'},
        { id:20, page : 'SRC', lang: 'ENG', texto:'Search for a Recipe'},
        { id:21, page : 'SRC', lang: 'SPA', texto:'Buscar una Receta'},
        { id:22, page : 'FIL', lang: 'ENG', texto:'Filter Diets'},
        { id:23, page : 'FIL', lang: 'SPA', texto:'Filtrar por Dietas'},
        { id:24, page : 'FIL', lang: 'ENG', texto:'Order by Recipe'},
        { id:25, page : 'FIL', lang: 'SPA', texto:'Ordenar Por Receta'},
        { id:26, page : 'FIL', lang: 'ENG', texto:'Order by Punctuation'},
        { id:27, page : 'FIL', lang: 'SPA', texto:'Ordenar Por Puntuacion'},
        { id:28, page : 'FIL', lang: 'ENG', texto:'Ascending'},
        { id:29, page : 'FIL', lang: 'SPA', texto:'Ascendente'},
        { id:30, page : 'FIL', lang: 'ENG', texto:'Descendig'},
        { id:31, page : 'FIL', lang: 'SPA', texto:'Descendente'},
        { id:32, page : 'FIL', lang: 'ENG', texto:'Filter'},
        { id:33, page : 'FIL', lang: 'SPA', texto:'Filtrar'},
        { id:34, page : 'FIL', lang: 'ENG', texto:'Clear'},
        { id:35, page : 'FIL', lang: 'SPA', texto:'Limpiar'},
        { id:36, page : 'FIL', lang: 'ENG', texto:'Clear All'},
        { id:37, page : 'FIL', lang: 'SPA', texto:'Limpiar Todo'},
        { id:38, page : 'SRC', lang: 'ENG', texto:'Clear'},
        { id:39, page : 'SRC', lang: 'SPA', texto:'Mostrar Todo'},
        { id:40, page : 'FOOD', lang: 'ENG', texto:'More Info'},
        { id:41, page : 'FOOD', lang: 'SPA', texto:'Ver Detalle'},
        { id:42, page : 'HOME', lang: 'ENG', texto:'Previous'},
        { id:43, page : 'HOME', lang: 'SPA', texto:'Anterior'},
        { id:44, page : 'HOME', lang: 'ENG', texto:'HOME'},
        { id:45, page : 'HOME', lang: 'SPA', texto:'Primero'},
        { id:46, page : 'HOME', lang: 'ENG', texto:'Next'},
        { id:47, page : 'HOME', lang: 'SPA', texto:'Proximo'},
        { id:48, page : 'FOOD', lang: 'ENG', texto:'Dish Types'},
        { id:49, page : 'FOOD', lang: 'SPA', texto:'Tipo de Plato'},
        { id:50, page : 'CREATE', lang: 'ENG', texto:'Title'},
        { id:51, page : 'CREATE', lang: 'SPA', texto:'Titulo'},
        { id:52, page : 'CREATE', lang: 'ENG', texto:'Summary'},
        { id:53, page : 'CREATE', lang: 'SPA', texto:'Resumen de la Receta'},
        { id:54, page : 'CREATE', lang: 'ENG', texto:'Food Health level'},
        { id:55, page : 'CREATE', lang: 'SPA', texto:'Puntos de Salud'},
        { id:56, page : 'CREATE', lang: 'ENG', texto:'Likes'},
        { id:57, page : 'CREATE', lang: 'SPA', texto:'Me gusta...'},
        { id:58, page : 'CREATE', lang: 'ENG', texto:'Instructions'},
        { id:59, page : 'CREATE', lang: 'SPA', texto:'Instruciones '},
        { id:60, page : 'CREATE', lang: 'ENG', texto:'Your Recipe was added to the Database.'},
        { id:61, page : 'CREATE', lang: 'SPA', texto:'Su receta fue agregada a la Base de datos'},
        { id:62, page : 'CREATE', lang: 'ENG', texto:'Could not create Recipe'},
        { id:63, page : 'CREATE', lang: 'SPA', texto:'No pude crear la receta'},
        { id:64, page : 'CREATE', lang: 'ENG', texto:'Ups... there was a problem'},
        { id:65, page : 'CREATE', lang: 'SPA', texto:'Hubo un problema en la grabacion'},
        { id:66, page : 'CREATE', lang: 'ENG', texto:'You have already selected this item'},
        { id:67, page : 'CREATE', lang: 'SPA', texto:'Ya has seleccionado este item'},
        { id:68, page : 'CREATE', lang: 'ENG', texto:'Youre recipe title'},
        { id:69, page : 'CREATE', lang: 'SPA', texto:'El titulo de su receta'},
        { id:70, page : 'CREATE', lang: 'ENG', texto:'Give me a little Summary'},
        { id:71, page : 'CREATE', lang: 'SPA', texto:'Ingrese un breve resumen'},
        { id:72, page : 'CREATE', lang: 'ENG', texto:'Dish Types'},
        { id:73, page : 'CREATE', lang: 'SPA', texto:'Tipo de plato'},
        { id:74, page : 'CREATE', lang: 'ENG', texto:'Create Recipe'},
        { id:75, page : 'CREATE', lang: 'SPA', texto:'Crear Receta'},
        { id:76, page : 'CREATE', lang: 'ENG', texto:'Choose Dish'},
        { id:77, page : 'CREATE', lang: 'SPA', texto:'Seleccione'},
        { id:78, page : 'NAV', lang: 'ENG', texto:'Language'},
        { id:79, page : 'NAV', lang: 'SPA', texto:'Idioma'},
        { id:80, page : 'CREATE',lang: 'ENG', texto:'Title is required'},
        { id:81, page : 'CREATE',lang: 'SPA', texto:'Titulo es requerido'},
        { id:82, page : 'CREATE',lang: 'ENG', texto:'Description is required'},
        { id:83, page : 'CREATE',lang: 'SPA', texto:'La descripicon es requerida'},
        { id:84, page : 'CREATE',lang: 'ENG', texto:'Food Health is required'},
        { id:85, page : 'CREATE',lang: 'SPA', texto:'Puntos de salud es requerida'},
        { id:86, page : 'CREATE',lang: 'ENG', texto:'Sorry Helth Score is from 0 to 999'},
        { id:87, page : 'CREATE',lang: 'SPA', texto:'Puntos de Salud debe ser entre 1 to 999'},
        { id:88, page : 'CREATE',lang: 'ENG', texto:'Likes is required'},
        { id:89, page : 'CREATE',lang: 'SPA', texto:'Me gusta es requerida'},
        { id:90, page : 'CREATE',lang: 'ENG', texto:'Instructions is required'},
        { id:91, page : 'CREATE',lang: 'SPA', texto:'Instrucciones es requerida'},
        ]).then(() => console.log("Idiomas ha sido grabado"));
       
    return "ok";
}

module.exports = idiomaLoad;


